"""add_jutsu_tables_and_door_auth_mode

Revision ID: aeff7182bd97
Revises: 2cb3b626efa4
Create Date: 2026-05-28 23:47:34.029809

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aeff7182bd97"
down_revision: Union[str, Sequence[str], None] = "2cb3b626efa4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jutsu",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("signs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_jutsu_name"), "jutsu", ["name"], unique=True)
    op.create_table(
        "door_jutsu",
        sa.Column("door_id", sa.Uuid(), nullable=False),
        sa.Column("jutsu_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["door_id"],
            ["door.id"],
        ),
        sa.ForeignKeyConstraint(
            ["jutsu_id"],
            ["jutsu.id"],
        ),
        sa.PrimaryKeyConstraint("door_id", "jutsu_id"),
    )
    op.add_column(
        "door",
        sa.Column(
            "auth_mode", sa.String(length=16), nullable=False, server_default="face"
        ),
    )
    op.create_index(op.f("ix_user_role_id"), "user", ["role_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_role_id"), table_name="user")
    op.drop_column("door", "auth_mode")
    op.drop_table("door_jutsu")
    op.drop_index(op.f("ix_jutsu_name"), table_name="jutsu")
    op.drop_table("jutsu")
    # ### end Alembic commands ###
